# AdvancedBan v2 - Coded by Leoko
# For each setting there is a small description
# please read it carefully before changing anything
# For more information visit: https://www.spigotmc.org/resources/advancedban.8695/
# Do you want your own Plugin or Website, check out our Dev-Page: http://dev.skamps.eu

# If set to false all bans will be saved locally in the data.yml
UseMySQL: false

# Set to false if you want to have only short messages in the console
# On startup and on the shutdown.
DetailedEnableMessage: true
DetailedDisableMessage: true

# Change this if your server has a diffrent time that your users.
# eg.: ServerTime: 16:43 | Your Time: 13:43 | TimeDiff has to be set to -3
# You can check the server time with /systemPerfs
TimeDiff: 0

# This commands will be disabled for muted players
# A player woun't be able to bypass with eg "/minectaft:me"
MuteCommands:
- 'me'
- 'say'

# The date-format which will be used for the %DATE% variable
DateFormat: "dd.MM.yyyy-HH:mm"

# If you use extern REST-APIs they will have to respond in JSON
# The given APIs will only be used for NAME -> UUID
# For UUID -> NAME will either the official MojangAPI or the InternFetcher be used!
# To check if you can use the intern fetcher do /systemPerfs and compare your uuid
#   to the one you can see online on http://NamesMC.com
#   if they are similar we recommend using the InternFetcher
UUID-Fetcher:
  # Disable for cracked servers
  Enabled: true
  Intern: false
  REST-API:
    URL: "https://api.mojang.com/users/profiles/minecraft/%NAME%?at=%TIMESTAMP%"
    Key: "id"
  BackUp-API:
    URL: "https://us.mc-api.net/v3/uuid/%NAME%"
    Key: "uuid"

# These are the commands that will be performed on warns
# If you skip a number the command from before will be performed
# You can also use not-AdvancedBan-Commands like 'broadcast' or 'clear %PLAYER%
# Variables: %PLAYER%, %REASON%, %COUNT%
WarnActions:
  3: "kick %PLAYER% &c&oYou received the 3th warning!"
  4: "tempban %PLAYER% 30m &c&oYou received the 4th warning!"
  5: "tempban %PLAYER% 5h &c&oYou received the 5th warning!"
  6: "tempban %PLAYER% 7d &c&oYou resived the 6th warning!"
  7: "tempban %PLAYER% 1mo &c&oYou received the %COUNT%th warning!"
  10: "ban %PLAYER% &c&oYou received the 10th warning!"

# Here you can create permission-nodes for max-punishment-duration.
# The permission "ab.tempban.dur.1" would allow the player to ban max. for 600sec = 10min
# The permission "ab.tempwarn.dur.2" would allow the player to warn max. for 3600sec = 1h
# You can only create up to 10 perms. The perms can be overridden with "ab.COMMAND.dur.max"
TempPerms:
  1: 600
  2: 3600
  3: 43200